### ISSUE TITLE
Rendering single option story within page

### ISSUE THREAD

**Issue by mhagendoorn-9292** [adliance/Storyblok#14]
Hi,

I've been trying to figure out how to render a single option story in a page. So far; I've been unsuccessful and I hope that someone can point me in the right direction. At this point, I'm even wondering if this SDK supports this?

My steps so far:

1. In Storyblok, add single option to page, make sure it's filled
2. In Program.cs, add `options.ResolveRelations = "navigation";` when calling the Middleware, so that it resolves the relations properly
3. In the pagemodel (`HomeTemplate.cs` in this case), instead of adding a component, add a `StoryblokStory` so that the model looks like this:

```csharp
[StoryblokComponent("homepage_template", "HomepageTemplate")]
public class HomepageTemplate : StoryblokComponent
{
    [JsonPropertyName("navigation")]
    public StoryblokStory Navigation { get; set; }

    [JsonPropertyName("fixed")]
    public StoryblokComponent[] Fixed { get; set; }

    [JsonPropertyName("body")]
    public StoryblokComponent[] Body { get; set; }

}
```
4. Create a `Navigation.cs` and `Navigation.cshtml` file in the correct place, with `Navigation.cs` looking like this:
```csharp
[StoryblokComponent("navigation")]
public class Navigation : StoryblokComponent
{
    [JsonPropertyName("items")]
    public StoryblokComponent[] Items { get; set; }
}

```

Now, the problems begin. In my `HomeTemplate.cshtml`, I try to render the view correctly. Problem is: I have absolutely no idea how. When I try to do it like this: `@Html.DisplayFor(x => x.Content.Navigation.Content)`, nothing happens. I'm guessing that's because `DisplayFor` expects a array, while `.Navigation.Content` only is a single `StoryblokComponent`.

Is there someone that can point me in the right direction? I've been pulling my hairs out of my head for days now, and I just can't seem to fix this.

**Comment by saxx** [comment]
I'm not entirely sure if I understand your question correctly, but it seems that you want to use a ASP.NET Razor ViewComponent to render a `StoryblokComponent` via `@Html.DisplayFor`?

This should actually work fine, as this only relies on out-of-the-box ViewComponent functionality (nothing special related to Storyblok SDK here), you just need to make sure that ASP.NET can find the ViewComponent (Naming needs to be correct, see https://learn.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-7.0

I think the issue is with the type of your `Navigation` property. You have `StoryblokStory` specified as a type, but shouldn't it be your custom type `Navigation`. `StoryblokStory` is usually to top-level wrapper type for the entire Storyblok response, usually you only want to work with `StoryblokComponent` and its subclasses.

Please take a look at https://github.com/adliance/Storyblok/blob/c97cc25ad104138a5c6af1145810d7a2f2b99079/test/Adliance.Storyblok.Tests/Clients/StoryblokStoryClientTest.cs (especially the test `Can_Load_Story_With_Resolved_Stories`) which - I think - does the thing you want (load a story with other stories resolved).

**Comment by saxx** [comment]
@mhagendoorn-9292 Thank you very much for the detailled answer. This is a use case that we haven't considered before (but it should work nonetheless).

My first suggestion would have been your 
````
@Html.DisplayFor(x => Model.Content.NavigationStory.Content)
````

So, if I understand you correctly, it works now on your end?

**Comment by mhagendoorn-9292** [comment]
@saxx Yes, it works now!
